import AppKit
import Foundation
import AMURWEBScanCore

@MainActor
struct MockScannerBackend: ScannerBackend {
    let backendName = "Mock Scanner"
    private let namer = ScanFileNamer()

    func listDevices() async throws -> [ScannerDevice] {
        try await Task.sleep(nanoseconds: 120_000_000)
        return [
            ScannerDevice(id: "mock-flatbed", name: "AMURWEB Virtual Scanner", isMock: true),
            ScannerDevice(id: "mock-adf", name: "AMURWEB Virtual ADF", isMock: true)
        ]
    }

    func scan(_ request: ScanRequest) async throws -> ScanResult {
        try FileManager.default.createDirectory(at: request.outputFolder, withIntermediateDirectories: true)
        try await Task.sleep(nanoseconds: 450_000_000)

        let useADF = request.device.id == "mock-adf" || request.source == .documentFeeder
        let pageCount = useADF ? (request.duplexEnabled ? 4 : 3) : 1
        let images = (1...pageCount).map { page in
            makeMockPage(request: request, page: page, pageCount: pageCount)
        }

        if request.format == .pdf {
            let outputURL = namer.nextFileURL(
                in: request.outputFolder,
                format: .pdf,
                language: request.language
            )
            try ImageOutputWriter.write(images: images, to: outputURL, format: .pdf)
            return ScanResult(fileURL: outputURL, deviceName: request.device.name)
        }

        var outputURLs: [URL] = []
        for image in images {
            let outputURL = namer.nextFileURL(
                in: request.outputFolder,
                format: request.format,
                language: request.language
            )
            try ImageOutputWriter.write(image: image, to: outputURL, format: request.format)
            outputURLs.append(outputURL)
        }
        return ScanResult(fileURLs: outputURLs, deviceName: request.device.name)
    }

    private func makeMockPage(request: ScanRequest, page: Int, pageCount: Int) -> NSImage {
        let size = NSSize(width: 1240, height: 1754)
        let image = NSImage(size: size)
        image.lockFocus()
        defer { image.unlockFocus() }

        NSColor.white.setFill()
        NSRect(origin: .zero, size: size).fill()

        NSColor(calibratedWhite: 0.96, alpha: 1).setFill()
        NSBezierPath(roundedRect: NSRect(x: 72, y: 72, width: size.width - 144, height: size.height - 144), xRadius: 26, yRadius: 26).fill()

        let sourceText: String
        switch request.source {
        case .automatic: sourceText = "Automatic"
        case .flatbed: sourceText = "Flatbed"
        case .documentFeeder: sourceText = "ADF"
        }

        let title = "AMURWEB Scan · macOS 0.3.0 Alpha"
        let body = "Virtual scan page \(page) of \(pageCount)\n\nDevice: \(request.device.name)\nSource: \(sourceText)\nDPI: \(request.dpi)\nMode: \(request.colorMode.rawValue)\nFormat: \(request.format.rawValue.uppercased())\nDuplex: \(request.duplexEnabled ? "ON" : "OFF")\n\nThis page was generated by Mock Scanner."

        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 44, weight: .bold),
            .foregroundColor: NSColor(calibratedRed: 0.96, green: 0.57, blue: 0.04, alpha: 1)
        ]
        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.monospacedSystemFont(ofSize: 26, weight: .regular),
            .foregroundColor: NSColor(calibratedWhite: 0.18, alpha: 1)
        ]

        (title as NSString).draw(at: NSPoint(x: 130, y: 1450), withAttributes: titleAttrs)
        (body as NSString).draw(in: NSRect(x: 130, y: 650, width: 980, height: 760), withAttributes: bodyAttrs)

        NSColor(calibratedRed: 0.96, green: 0.57, blue: 0.04, alpha: 1).setFill()
        NSRect(x: 130, y: 600, width: 980, height: 8).fill()

        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 20, weight: .medium),
            .foregroundColor: NSColor(calibratedWhite: 0.45, alpha: 1)
        ]
        ("awc-dv.ru · info@awc-dv.ru" as NSString).draw(at: NSPoint(x: 130, y: 190), withAttributes: footerAttrs)

        return image
    }
}
