import AppKit
import Foundation
import AMURWEBScanCore

@MainActor
struct MockScannerBackend: ScannerBackend {
    let backendName = "Mock Scanner"
    private let namer = ScanFileNamer()

    func listDevices() async throws -> [ScannerDevice] {
        try await Task.sleep(nanoseconds: 120_000_000)
        return [
            ScannerDevice(id: "mock-flatbed", name: "AMURWEB Virtual Scanner", isMock: true),
            ScannerDevice(id: "mock-adf", name: "AMURWEB Virtual ADF", isMock: true)
        ]
    }

    func scan(_ request: ScanRequest) async throws -> ScanResult {
        try FileManager.default.createDirectory(at: request.outputFolder, withIntermediateDirectories: true)
        try await Task.sleep(nanoseconds: 450_000_000)

        let outputURL = namer.nextFileURL(
            in: request.outputFolder,
            format: request.format,
            language: request.language
        )

        let image = makeMockPage(request: request)
        try ImageOutputWriter.write(image: image, to: outputURL, format: request.format)
        return ScanResult(fileURL: outputURL, deviceName: request.device.name)
    }

    private func makeMockPage(request: ScanRequest) -> NSImage {
        let size = NSSize(width: 1240, height: 1754)
        let image = NSImage(size: size)
        image.lockFocus()
        defer { image.unlockFocus() }

        NSColor.white.setFill()
        NSRect(origin: .zero, size: size).fill()

        NSColor(calibratedWhite: 0.96, alpha: 1).setFill()
        NSBezierPath(roundedRect: NSRect(x: 72, y: 72, width: size.width - 144, height: size.height - 144), xRadius: 26, yRadius: 26).fill()

        let title = "AMURWEB Scan · macOS 0.2.0 Alpha"
        let body = "Virtual scan page\n\nDevice: \(request.device.name)\nDPI: \(request.dpi)\nMode: \(request.colorMode.rawValue)\nFormat: \(request.format.rawValue.uppercased())\n\nThis page was generated by Mock Scanner."

        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 44, weight: .bold),
            .foregroundColor: NSColor(calibratedRed: 0.96, green: 0.57, blue: 0.04, alpha: 1)
        ]
        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.monospacedSystemFont(ofSize: 26, weight: .regular),
            .foregroundColor: NSColor(calibratedWhite: 0.18, alpha: 1)
        ]

        (title as NSString).draw(at: NSPoint(x: 130, y: 1450), withAttributes: titleAttrs)
        (body as NSString).draw(in: NSRect(x: 130, y: 720, width: 980, height: 650), withAttributes: bodyAttrs)

        NSColor(calibratedRed: 0.96, green: 0.57, blue: 0.04, alpha: 1).setFill()
        NSRect(x: 130, y: 620, width: 980, height: 8).fill()

        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: NSFont.systemFont(ofSize: 20, weight: .medium),
            .foregroundColor: NSColor(calibratedWhite: 0.45, alpha: 1)
        ]
        ("awc-dv.ru · info@awc-dv.ru" as NSString).draw(at: NSPoint(x: 130, y: 190), withAttributes: footerAttrs)

        return image
    }
}
