import Foundation

public enum L10n {
    private static let ru: [String: String] = [
        "app.subtitle": "Современное сканирование без лишних действий",
        "badge.free": "БЕСПЛАТНО",
        "badge.offline": "ЛОКАЛЬНЫЕ ФАЙЛЫ",
        "badge.mac": "macOS",
        "badge.mock": "MOCK",
        "badge.hardware": "СКАНЕР",
        "scanner": "Сканер",
        "source": "Источник",
        "source.auto": "Автоматически",
        "source.flatbed": "Планшет",
        "source.adf": "Автоподатчик (ADF)",
        "duplex": "Двустороннее сканирование",
        "resolution": "Разрешение",
        "mode": "Режим",
        "format": "Формат",
        "color": "Цветной",
        "grayscale": "Оттенки серого",
        "bw": "Текст / ЧБ",
        "multipage.manual": "Многостраничный PDF с планшета",
        "multipage.manualNote": "После каждой страницы программа предложит положить следующую. В конце все страницы будут собраны в один PDF.",
        "multipage.adfAuto": "Для ADF многостраничный PDF формируется автоматически из всей пачки.",
        "multipage.pageScanned": "Страница %d отсканирована",
        "multipage.nextPrompt": "Положите следующую страницу на стекло сканера. Выберите «Следующая страница», чтобы продолжить, или «Готово», чтобы собрать один PDF.",
        "multipage.next": "Следующая страница",
        "multipage.finish": "Готово",
        "folder": "Папка сохранения",
        "choose.folder": "Выбрать папку в Finder",
        "open.folder": "Открыть папку",
        "next.file": "Следующий файл",
        "scan": "СКАНИРОВАТЬ",
        "cancel": "Отменить сканирование",
        "close": "Закрыть",
        "later": "Позже",
        "refresh": "Обновить сканеры",
        "preview": "Предпросмотр",
        "preview.empty.title": "Документ появится здесь",
        "preview.empty.body": "Выберите реальный сканер, найденный через ImageCaptureCore, или виртуальный Mock Scanner для проверки интерфейса, ADF, ручного многостраничного PDF и сохранения без оборудования.",
        "status.ready": "Готово к сканированию",
        "status.scanning": "Сканирование…",
        "status.cancelling": "Отмена сканирования…",
        "status.cancelled": "Сканирование отменено",
        "status.saved": "Сохранено",
        "status.mock": "Режим тестирования: Mock Scanner",
        "status.hardware": "Реальный сканер через ImageCaptureCore",
        "menu.scan": "Сканирование",
        "menu.scan.now": "Сканировать сейчас",
        "menu.cancel": "Отменить сканирование",
        "menu.refresh": "Обновить устройства",
        "menu.language": "Язык",
        "menu.help": "Справка",
        "menu.about": "О программе",
        "menu.support": "Техподдержка",
        "menu.diagnostics": "Диагностика сканера",
        "menu.checkUpdates": "Проверить обновления…",
        "menu.legal": "Правовая информация",
        "diagnostics.title": "Диагностика сканера",
        "diagnostics.body": "Этот отчёт помогает техподдержке проверить, что macOS и ImageCaptureCore видят сканер и какие возможности сообщает устройство.",
        "diagnostics.loading": "Собираем сведения об устройствах…",
        "diagnostics.refresh": "Обновить отчёт",
        "diagnostics.copy": "Копировать отчёт",
        "about.developer": "Разработчик: Амурский Веб Центр (АМУРВЕБ)",
        "about.description": "AMURWEB Scan — бесплатное приложение для удобного сканирования документов. Версия для macOS разрабатывается как нативное приложение и не зависит от Mac App Store.",
        "support.title": "Техподдержка AMURWEB Scan",
        "support.body": "Если вы обнаружили неисправность, у вас возник вопрос или есть предложение по работе AMURWEB Scan, напишите в техподдержку. Для вопросов по конкретному сканеру укажите модель устройства и версию macOS. По возможности приложите отчёт из раздела «Диагностика сканера».",
        "program.page": "Страница программы",
        "go": "Перейти",
        "promotion.header": "ПРОДУКТЫ ЭКОСИСТЕМЫ AMURWEB",
        "promotion.more": "Подробнее",
        "promotion.privacy": "Промо показывается по локальному счётчику запусков. История показов и кликов на сервер не отправляется.",
        "settings.checkUpdates": "Автоматически проверять новые версии",
        "settings.checkUpdates.note": "Не чаще одного раза в сутки. Проверяется только номер доступной версии. Документы и данные сканирования не передаются.",
        "updates.available.title": "Доступна новая версия %@",
        "updates.available.body": "Вышла новая версия AMURWEB Scan. Откройте страницу программы, чтобы посмотреть изменения и скачать её.",
        "updates.open": "Подробнее",
        "updates.current.title": "Обновлений нет",
        "updates.current.body": "У вас установлена актуальная версия AMURWEB Scan %@.",
        "updates.error.title": "Не удалось проверить обновления",
        "updates.error.body": "Сервер обновлений сейчас недоступен. Это не влияет на сканирование — попробуйте проверить позже.",
        "legal.title": "Правовая информация",
        "legal.body": "AMURWEB Scan распространяется бесплатно. Все права на программу, название и визуальные материалы принадлежат Амурскому Веб Центру (АМУРВЕБ). Программа предоставляется «как есть». Совместимость со сканерами зависит от macOS, драйверов и возможностей конкретного устройства. Отсканированные документы обрабатываются и сохраняются локально. Приложение может отдельно проверять наличие новых версий и загружать каталог продуктов AMURWEB, но содержимое документов на сервер не передаётся.",
        "alpha.notice": "0.6.0 Alpha · ручной многостраничный PDF без ADF · требуется внешний тест на реальном Mac и сканере",
        "error": "Ошибка",
        "error.noDevice": "Сканер не выбран. Обновите список устройств и выберите сканер.",
        "error.noFolder": "Не выбрана папка для сохранения. Укажите папку в Finder.",
        "error.unsupported": "Выбранная функция не поддерживается этим сканером.",
        "error.scanFailed": "Не удалось выполнить сканирование. Проверьте подключение сканера и его состояние."
    ]

    private static let en: [String: String] = [
        "app.subtitle": "Modern scanning without unnecessary steps",
        "badge.free": "FREE",
        "badge.offline": "LOCAL FILES",
        "badge.mac": "macOS",
        "badge.mock": "MOCK",
        "badge.hardware": "SCANNER",
        "scanner": "Scanner",
        "source": "Source",
        "source.auto": "Automatic",
        "source.flatbed": "Flatbed",
        "source.adf": "Document feeder (ADF)",
        "duplex": "Duplex scanning",
        "resolution": "Resolution",
        "mode": "Mode",
        "format": "Format",
        "color": "Color",
        "grayscale": "Grayscale",
        "bw": "Text / B&W",
        "multipage.manual": "Multi-page PDF from flatbed",
        "multipage.manualNote": "After each page, the app will ask you to place the next one. All pages are combined into one PDF when finished.",
        "multipage.adfAuto": "With ADF, a multi-page PDF is created automatically from the whole feeder job.",
        "multipage.pageScanned": "Page %d scanned",
        "multipage.nextPrompt": "Place the next page on the scanner glass. Choose “Next page” to continue or “Finish” to create one PDF.",
        "multipage.next": "Next page",
        "multipage.finish": "Finish",
        "folder": "Save folder",
        "choose.folder": "Choose folder in Finder",
        "open.folder": "Open folder",
        "next.file": "Next file",
        "scan": "SCAN",
        "cancel": "Cancel scan",
        "close": "Close",
        "later": "Later",
        "refresh": "Refresh scanners",
        "preview": "Preview",
        "preview.empty.title": "Your document will appear here",
        "preview.empty.body": "Choose a real scanner discovered through ImageCaptureCore, or use Mock Scanner to test the UI, ADF, manual multi-page PDF and file output without hardware.",
        "status.ready": "Ready to scan",
        "status.scanning": "Scanning…",
        "status.cancelling": "Cancelling scan…",
        "status.cancelled": "Scan cancelled",
        "status.saved": "Saved",
        "status.mock": "Test mode: Mock Scanner",
        "status.hardware": "Real scanner via ImageCaptureCore",
        "menu.scan": "Scan",
        "menu.scan.now": "Scan now",
        "menu.cancel": "Cancel scan",
        "menu.refresh": "Refresh devices",
        "menu.language": "Language",
        "menu.help": "Help",
        "menu.about": "About",
        "menu.support": "Support",
        "menu.diagnostics": "Scanner diagnostics",
        "menu.checkUpdates": "Check for updates…",
        "menu.legal": "Legal information",
        "diagnostics.title": "Scanner diagnostics",
        "diagnostics.body": "This report helps support verify that macOS and ImageCaptureCore can see the scanner and which capabilities the device reports.",
        "diagnostics.loading": "Collecting device information…",
        "diagnostics.refresh": "Refresh report",
        "diagnostics.copy": "Copy report",
        "about.developer": "Developer: Amur Web Center (AMURWEB)",
        "about.description": "AMURWEB Scan is a free application for convenient document scanning. The macOS edition is being developed as a native app and does not depend on the Mac App Store.",
        "support.title": "AMURWEB Scan Support",
        "support.body": "If you encounter a problem, have a question, or want to suggest an improvement, contact support. For scanner-specific issues, include your scanner model and macOS version. If possible, attach the report from Scanner diagnostics.",
        "program.page": "Program page",
        "go": "Open",
        "promotion.header": "AMURWEB ECOSYSTEM PRODUCTS",
        "promotion.more": "Learn more",
        "promotion.privacy": "Promotion timing is based on a local launch counter. Impression and click history is not sent to the server.",
        "settings.checkUpdates": "Automatically check for new versions",
        "settings.checkUpdates.note": "At most once per day. Only version metadata is checked. Documents and scan data are never uploaded.",
        "updates.available.title": "New version %@ is available",
        "updates.available.body": "A new AMURWEB Scan version is available. Open the product page to review changes and download it.",
        "updates.open": "Learn more",
        "updates.current.title": "No updates available",
        "updates.current.body": "AMURWEB Scan %@ is currently up to date.",
        "updates.error.title": "Unable to check for updates",
        "updates.error.body": "The update server is currently unavailable. Scanning is unaffected — try again later.",
        "legal.title": "Legal information",
        "legal.body": "AMURWEB Scan is distributed free of charge. All rights to the application, name and visual materials belong to Amur Web Center (AMURWEB). The software is provided as is. Scanner compatibility depends on macOS, device drivers and the capabilities of the specific scanner. Scanned documents are processed and stored locally. The app may separately check for new versions and retrieve the AMURWEB product catalog, but document contents are never uploaded.",
        "alpha.notice": "0.6.0 Alpha · manual multi-page PDF without ADF · external real-Mac scanner test required",
        "error": "Error",
        "error.noDevice": "No scanner is selected. Refresh the device list and choose a scanner.",
        "error.noFolder": "No save folder is selected. Choose a folder in Finder.",
        "error.unsupported": "The selected feature is not supported by this scanner.",
        "error.scanFailed": "Scanning failed. Check the scanner connection and device state."
    ]

    public static func text(_ key: String, language: AppLanguage) -> String {
        let table = language == .ru ? ru : en
        return table[key] ?? key
    }
}
