import Foundation

public enum L10n {
    private static let ru: [String: String] = [
        "app.subtitle": "Современное сканирование без лишних действий",
        "badge.free": "БЕСПЛАТНО",
        "badge.offline": "OFFLINE",
        "badge.mac": "macOS",
        "badge.mock": "MOCK",
        "badge.hardware": "СКАНЕР",
        "scanner": "Сканер",
        "resolution": "Разрешение",
        "mode": "Режим",
        "format": "Формат",
        "color": "Цветной",
        "grayscale": "Оттенки серого",
        "bw": "Текст / ЧБ",
        "folder": "Папка сохранения",
        "choose.folder": "Выбрать папку в Finder",
        "open.folder": "Открыть папку",
        "next.file": "Следующий файл",
        "scan": "СКАНИРОВАТЬ",
        "refresh": "Обновить сканеры",
        "preview": "Предпросмотр",
        "preview.empty.title": "Документ появится здесь",
        "preview.empty.body": "Выберите реальный сканер, найденный через ImageCaptureCore, или виртуальный Mock Scanner для проверки интерфейса и сохранения без оборудования.",
        "status.ready": "Готово к сканированию",
        "status.scanning": "Сканирование…",
        "status.saved": "Сохранено",
        "status.mock": "Режим тестирования: Mock Scanner",
        "status.hardware": "Реальный сканер через ImageCaptureCore",
        "menu.scan": "Сканирование",
        "menu.scan.now": "Сканировать сейчас",
        "menu.refresh": "Обновить устройства",
        "menu.language": "Язык",
        "menu.help": "Справка",
        "menu.about": "О программе",
        "menu.support": "Техподдержка",
        "menu.legal": "Правовая информация",
        "about.developer": "Разработчик: Амурский Веб Центр (АМУРВЕБ)",
        "about.description": "AMURWEB Scan — бесплатное приложение для удобного сканирования документов. Версия для macOS разрабатывается как нативное приложение и не зависит от Mac App Store.",
        "support.title": "Техподдержка AMURWEB Scan",
        "support.body": "Если вы обнаружили неисправность, у вас возник вопрос или есть предложение по работе AMURWEB Scan, напишите в техподдержку. Для вопросов по конкретному сканеру укажите модель устройства и версию macOS.",
        "program.page": "Страница программы",
        "go": "Перейти",
        "legal.title": "Правовая информация",
        "legal.body": "AMURWEB Scan распространяется бесплатно. Все права на программу, название и визуальные материалы принадлежат Амурскому Веб Центру (АМУРВЕБ). Программа предоставляется «как есть». Совместимость со сканерами зависит от macOS, драйверов и возможностей конкретного устройства. Отсканированные документы обрабатываются и сохраняются локально.",
        "alpha.notice": "0.2.0 Alpha · ImageCaptureCore включён · требуется внешний тест на реальном Mac и сканере",
        "error": "Ошибка"
    ]

    private static let en: [String: String] = [
        "app.subtitle": "Modern scanning without unnecessary steps",
        "badge.free": "FREE",
        "badge.offline": "OFFLINE",
        "badge.mac": "macOS",
        "badge.mock": "MOCK",
        "badge.hardware": "SCANNER",
        "scanner": "Scanner",
        "resolution": "Resolution",
        "mode": "Mode",
        "format": "Format",
        "color": "Color",
        "grayscale": "Grayscale",
        "bw": "Text / B&W",
        "folder": "Save folder",
        "choose.folder": "Choose folder in Finder",
        "open.folder": "Open folder",
        "next.file": "Next file",
        "scan": "SCAN",
        "refresh": "Refresh scanners",
        "preview": "Preview",
        "preview.empty.title": "Your document will appear here",
        "preview.empty.body": "Choose a real scanner discovered through ImageCaptureCore, or use Mock Scanner to test the interface and file output without hardware.",
        "status.ready": "Ready to scan",
        "status.scanning": "Scanning…",
        "status.saved": "Saved",
        "status.mock": "Test mode: Mock Scanner",
        "status.hardware": "Real scanner via ImageCaptureCore",
        "menu.scan": "Scan",
        "menu.scan.now": "Scan now",
        "menu.refresh": "Refresh devices",
        "menu.language": "Language",
        "menu.help": "Help",
        "menu.about": "About",
        "menu.support": "Support",
        "menu.legal": "Legal information",
        "about.developer": "Developer: Amur Web Center (AMURWEB)",
        "about.description": "AMURWEB Scan is a free application for convenient document scanning. The macOS edition is being developed as a native app and does not depend on the Mac App Store.",
        "support.title": "AMURWEB Scan Support",
        "support.body": "If you encounter a problem, have a question, or want to suggest an improvement, contact support. For scanner-specific issues, include your scanner model and macOS version.",
        "program.page": "Program page",
        "go": "Open",
        "legal.title": "Legal information",
        "legal.body": "AMURWEB Scan is distributed free of charge. All rights to the application, name and visual materials belong to Amur Web Center (AMURWEB). The software is provided as is. Scanner compatibility depends on macOS, device drivers and the capabilities of the specific scanner. Scanned documents are processed and stored locally.",
        "alpha.notice": "0.2.0 Alpha · ImageCaptureCore enabled · external real-Mac scanner test required",
        "error": "Error"
    ]

    public static func text(_ key: String, language: AppLanguage) -> String {
        let table = language == .ru ? ru : en
        return table[key] ?? key
    }
}
